site_name: ree-finder
site_description: Pipeline for predicting and refining metal binding sites in proteins
repo_url: https://github.com/msinclair-py/ree-finder
repo_name: msinclair-py/ree-finder

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src/ree-finder]
          options:
            docstring_style: google
            allow_inspection: false
            show_source: true
            show_root_heading: true
            show_signature_annotations: true
            separate_signature: true
            merge_init_into_class: true
            members_order: source
            filters: ["!^_"]

nav:
  - Home: index.md
  - API Reference:
      - Overview: api/index.md
      - pipeline: api/pipeline.md
      - apps: api/apps.md
      - dataset: api/dataset.md
      - model: api/model.md
      - schemas: api/schemas.md
      - defaults: api/defaults.md
